version: '3.8'

services:
  # 1. Веб-сервер (Frontend/Proxy)
  web:
    image: nginx:alpine
    container_name: music_web
    restart: always
    ports:
      - "3000:80"  # Доступ з браузера по http://localhost:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  # 2. Бекенд (Flask додаток)
  api:
    build: .
    container_name: music_api
    restart: always
    ports:
      - "8080:8080" # Можна залишити для прямого доступу
    environment:
      - FLASK_ENV=production
    volumes:
      - music_data:/app/static/music
      - covers_data:/app/static/covers
      - db_sqlite:/app/instance 
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: music_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  music_data:
  covers_data:
  db_sqlite: